In [1]:
from glob import glob
import json
import pandas as pd
import numpy as np
from IPython.display import display_html

In [2]:
results = [json.load(open(f)) for f in glob("set_rank_results_cifar10/*.json")]
results = pd.DataFrame(results)

results["best_loss"] = results["loss"].map(np.min)
results["best_loss_epoch"] = results["loss"].map(lambda x: np.argmin(x) + 1)
results["best_categorical_accuracy"] = results["categorical_accuracy"].map(np.max)
results["best_categorical_accuracy_epoch"] = results["categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["best_val_loss"] = results["val_loss"].map(np.min)
results["best_val_loss_epoch"] = results["val_loss"].map(lambda x: np.argmin(x) + 1)
results["best_val_categorical_accuracy"] = results["val_categorical_accuracy"].map(np.max)
results["best_val_categorical_accuracy_epoch"] = results["val_categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["initial_rank"].replace(-1, 256, inplace=True)
results["new_rank"].replace(-1, 256, inplace=True)
results.head()

,initial_rank,new_rank,rank_update_epoch,total_epochs,loss,categorical_accuracy,val_loss,val_categorical_accuracy,pre_update_loss,pre_update_categorical_accuracy,...,post_update_val_loss,post_update_val_categorical_accuracy,best_loss,best_loss_epoch,best_categorical_accuracy,best_categorical_accuracy_epoch,best_val_loss,best_val_loss_epoch,best_val_categorical_accuracy,best_val_categorical_accuracy_epoch
0,200,1,25,50,"[1.6945616006851196, 1.3467351198196411, 1.185...","[0.3723999857902527, 0.5099200010299683, 0.574...","[1.4748198986053467, 1.2428358793258667, 1.185...","[0.45649999380111694, 0.5493000149726868, 0.57...",0.101661,0.96734,...,2.106575,0.1830,0.125470,25,0.95858,25,0.695949,17,0.7775,24
1,1,200,25,50,"[1.9884175062179565, 1.8690537214279175, 1.842...","[0.17518000304698944, 0.2015399932861328, 0.20...","[1.8942424058914185, 1.8421685695648193, 1.835...","[0.19429999589920044, 0.20469999313354492, 0.2...",1.119931,0.53476,...,1.503841,0.4341,0.086989,49,0.97082,49,0.995005,33,0.7267,50
2,4,4,1,50,"[1.8733692169189453, 1.5795079469680786, 1.467...","[0.2890799939632416, 0.398140013217926, 0.4439...","[1.6671442985534668, 1.5272045135498047, 1.487...","[0.36809998750686646, 0.4235000014305115, 0.43...",1.670200,0.36016,...,1.667161,0.3680,0.068136,50,0.97778,50,0.814334,27,0.7295,33
3,53,200,2,50,"[1.703080177307129, 1.3980000019073486, 1.2670...","[0.3668400049209595, 0.48848000168800354, 0.53...","[1.5254783630371094, 1.3288847208023071, 1.187...","[0.4300999939441681, 0.5163999795913696, 0.573...",1.328509,0.51318,...,1.328893,0.5163,0.024365,49,0.99210,49,0.705702,18,0.7741,50
4,256,1,5,50,"[1.7061458826065063, 1.3607358932495117, 1.217...","[0.3745200037956238, 0.5076599717140198, 0.566...","[1.4480233192443848, 1.241896390914917, 1.1797...","[0.48159998655319214, 0.5575000047683716, 0.58...",1.060793,0.62576,...,2.129262,0.1699,0.643196,50,0.74418,50,1.075168,4,0.6241,4

In [3]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3844 entries, 0 to 3843
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   initial_rank                          3844 non-null   int64
 1   new_rank                              3844 non-null   int64
 2   rank_update_epoch                     3844 non-null   int64
 3   total_epochs                          3844 non-null   int64
 4   loss                                  3844 non-null   object
 5   categorical_accuracy                  3844 non-null   object
 6   val_loss                              3844 non-null   object
 7   val_categorical_accuracy              3844 non-null   object
 8   pre_update_loss                       3844 non-null   float64
 9   pre_update_categorical_accuracy       3844 non-null   float64
 10  pre_update_val_loss                   3844 non-null   float64
 11  pre_update_val_categorical_accuracy   3844 non-null   float64
 12  post_update_loss                      3844 non-null   float64
 13  post_update_categorical_accuracy      3844 non-null   float64
 14  post_update_val_loss                  3844 non-null   float64
 15  post_update_val_categorical_accuracy  3844 non-null   float64
 16  best_loss                             3844 non-null   float64
 17  best_loss_epoch                       3844 non-null   int64
 18  best_categorical_accuracy             3844 non-null   float64
 19  best_categorical_accuracy_epoch       3844 non-null   int64
 20  best_val_loss                         3844 non-null   float64
 21  best_val_loss_epoch                   3844 non-null   int64
 22  best_val_categorical_accuracy         3844 non-null   float64
 23  best_val_categorical_accuracy_epoch   3844 non-null   int64
dtypes: float64(12), int64(8), object(4)
memory usage: 720.9+ KB

In [4]:
np.argmax(results["best_val_categorical_accuracy"])

1098

In [5]:
results.iloc[55]

initial_rank                                                                           14
new_rank                                                                              200
rank_update_epoch                                                                      10
total_epochs                                                                           50
loss                                    [1.8028253316879272, 1.4960806369781494, 1.363...
categorical_accuracy                    [0.3247399926185608, 0.4496400058269501, 0.503...
val_loss                                [1.569806694984436, 1.43424654006958, 1.282783...
val_categorical_accuracy                [0.41990000009536743, 0.47909998893737793, 0.5...
pre_update_loss                                                                  0.848009
pre_update_categorical_accuracy                                                    0.7043
pre_update_val_loss                                                              0.910688
pre_update_val_categorical_accuracy                                                0.6844
post_update_loss                                                                 0.847985
post_update_categorical_accuracy                                                  0.70436
post_update_val_loss                                                             0.910665
post_update_val_categorical_accuracy                                               0.6845
best_loss                                                                        0.033977
best_loss_epoch                                                                        49
best_categorical_accuracy                                                         0.98944
best_categorical_accuracy_epoch                                                        49
best_val_loss                                                                    0.689377
best_val_loss_epoch                                                                    24
best_val_categorical_accuracy                                                      0.7774
best_val_categorical_accuracy_epoch                                                    49
Name: 55, dtype: object

In [6]:
display(results["initial_rank"].unique())
display(results["new_rank"].unique())
display(results["rank_update_epoch"].unique())

array([200,   1,   4,  53, 256,  14])

array([  1, 200,   4, 256,  53,  14])

array([25,  1,  2,  5, 10])

In [7]:
len(results)

3844

In [8]:
def visualize(column: str, rank_update_epoch: int):
    avg_results = pd.pivot_table(
        results.loc[
            results["rank_update_epoch"] == rank_update_epoch,
            ["initial_rank", "new_rank", column]
        ],
        index="initial_rank",
        columns="new_rank",
    )
    count_results = pd.pivot_table(
        results.loc[
            results["rank_update_epoch"] == rank_update_epoch,
            ["initial_rank", "new_rank", column]
        ],
        index="initial_rank",
        columns="new_rank",
        fill_value=0,
        aggfunc=len
    )
    display_html(
        avg_results
            .style
            .background_gradient(cmap='Blues', axis=None, vmin=0.77)
            .format("{:.3f}")
            .set_table_attributes("style='display:inline'")
            .set_caption("Avg")
            .set_properties(width="40px", height="40px")
            ._repr_html_() + \
        count_results
            .style
            .background_gradient(cmap='Blues', axis=None)
            .format("{:.0f}")
            .set_table_attributes("style='display:inline'")
            .set_caption("Count")
            .set_properties(width="40px", height="40px")
            ._repr_html_(),
        raw=True
    )

In [9]:
for rank_update_epoch in np.sort(results["rank_update_epoch"].unique()):
    print(f"Rank updated on epoch: {rank_update_epoch}")
    visualize("best_val_categorical_accuracy", rank_update_epoch)

Rank updated on epoch: 1

Rank updated on epoch: 2

Rank updated on epoch: 5

Rank updated on epoch: 10

Rank updated on epoch: 25